#    ███╗░░██╗██╗░██████╗░██╗░░██╗████████╗        ██╗░░░██╗██╗░██████╗██╗░█████╗░███╗░░██╗
#    ████╗░██║██║██╔════╝░██║░░██║╚══██╔══╝        ██║░░░██║██║██╔════╝██║██╔══██╗████╗░██║
#    ██╔██╗██║██║██║░░██╗░███████║░░░██║░░░        ╚██╗░██╔╝██║╚█████╗░██║██║░░██║██╔██╗██║
#    ██║╚████║██║██║░░╚██╗██╔══██║░░░██║░░░        ░╚████╔╝░██║░╚═══██╗██║██║░░██║██║╚████║
#    ██║░╚███║██║╚██████╔╝██║░░██║░░░██║░░░        ░░╚██╔╝░░██║██████╔╝██║╚█████╔╝██║░╚███║
#    ╚═╝░░╚══╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░        ░░░╚═╝░░░╚═╝╚═════╝░╚═╝░╚════╝░╚═╝░░╚══╝

# Core Settings
use-permissions: false
effect-duration: -1  # Duration in seconds (-1 = infinite)
apply-on-join: true
show-particles: false

# Message Settings
messages:
# if set to false chat messages won't appear
  enabled: true
  enabled-text: "&a&lNight Vision Enabled"
  disabled-text: "&c&lNight Vision Disabled"

# Title Settings
titles:
# id set to false action bar titles won't appear
  enabled: true
  enabled-text: "&7Night Vision &aON"
  disabled-text: "&7Night Vision &cOFF"