

#    ███╗░░██╗██╗░██████╗░██╗░░██╗████████╗        ██╗░░░██╗██╗░██████╗██╗░█████╗░███╗░░██╗
#    ████╗░██║██║██╔════╝░██║░░██║╚══██╔══╝        ██║░░░██║██║██╔════╝██║██╔══██╗████╗░██║
#    ██╔██╗██║██║██║░░██╗░███████║░░░██║░░░        ╚██╗░██╔╝██║╚█████╗░██║██║░░██║██╔██╗██║
#    ██║╚████║██║██║░░╚██╗██╔══██║░░░██║░░░        ░╚████╔╝░██║░╚═══██╗██║██║░░██║██║╚████║
#    ██║░╚███║██║╚██████╔╝██║░░██║░░░██║░░░        ░░╚██╔╝░░██║██████╔╝██║╚█████╔╝██║░╚███║
#    ╚═╝░░╚══╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░        ░░░╚═╝░░░╚═╝╚═════╝░╚═╝░╚════╝░╚═╝░░╚══╝


# Chat message when toggled (set to "" to disable)
messages:
  enabled: "&a&lNight Vision Enabled"
  disabled: "&c&lNight Vision Disabled"

# Title message when toggled (set to "" to disable)
  title_enabled: "&7Night Vision &aON"
  title_disabled: "&7Night Vision &cOFF"
